# Generated by Django 4.0.3 on 2022-04-04 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('date_pub', models.DateField()),
                ('number_ISBN', models.IntegerField()),
                ('pages', models.IntegerField()),
                ('book_covers', models.URLField()),
                ('language', models.CharField(max_length=100)),
            ],
        ),
    ]
